// Generated by js_of_ocaml
//# buildInfo:effects=true, kind=cmo, use-js-string=true, version=5.7.1+5.7.1

//# unitInfo: Provides: Dune__exe__Graphics_support
//# unitInfo: Requires: Graphics_js
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_cps_call2(f, a0, a1){
    return runtime.caml_stack_check_depth()
            ? (f.l
                >= 0
                ? f.l
                : f.l = f.length)
              == 2
              ? f(a0, a1)
              : runtime.caml_call_gen(f, [a0, a1])
            : runtime.caml_trampoline_return(f, [a0, a1]);
   }
   runtime.jsoo_create_file
    ("/static/cmis/dune__exe__Graphics_support.cmi",
     "Caml1999I032\x84\x95\xa6\xbe\0\0\0\xc5\0\0\0&\0\0\0\x8e\0\0\0\x82\xa0;Dune__exe__Graphics_support\xa0\xb0\xa0$init\x01\x04[\xd0\xc0\xc1@\xc0\xb3\xa1\xa1\x90\x92+Js_of_ocaml\"Js!t\xa0\xc0\xb3\xa1\xa1\x04\n(Dom_html-canvasElement@\x90@\x02\x05\xf5\xe1\0@\0\xfb@\x90@\x02\x05\xf5\xe1\0@\0\xfc\xc0\xb3\x90\xa3$unitF@\x90@\x02\x05\xf5\xe1\0@\0\xfd@\x02\x05\xf5\xe1\0@\0\xfe@\xb0\xc0;graphics_support.enabled.mlAbf\xc0\x04\x02Abj@@\xa1\x04%@@@\x84\x95\xa6\xbe\0\0\x02\xa2\0\0\0_\0\0\x01n\0\0\x01%\xa0\xa0;Dune__exe__Graphics_support\x900ZI\x0ej\xe3\x97\xb5+\x03%5\x9c\x83[\x9co\xa0\xa0-Stdlib__Uchar\x900\x9e\xa8d\bP\x95\x97\fs\xb7\xb1|&\xc3s\x17\xa0\xa0/Stdlib__Complex\x900\xd5\xf0A\xcc\xbe\x97\x83\xaf\x90\xca83p\x02\xfbN\xa0\xa00Stdlib__Bigarray\x900U\xa8\x12\xd9\xa3\xc8\x9ez\x8e\xbb\x91~c\xe4\xbe\xea\xa0\xa0&Stdlib\x900\x85\xf8]\xdbG\xed\xc0\xc7W\x96W\xee\xe7@0-\xa0\xa0,Lwt_sequence\x900S\x1e\xcb\xf9\x05\xeb\xc7#\x0e\x94\x17d\xa5^\xe6\x94\xa0\xa0#Lwt\x900Y\xbb\xd3Ptz\x1c\x8a\x19ua\xc2\xee6\x14p\xa0\xa08Js_of_ocaml__Typed_array\x900[W\xdd\xe9!\xd8\x0b\xa9\x81\x16\xf4j\x8e-\xd2\x9b\xa0\xa0/Js_of_ocaml__Js\x900;\xf2\xa5\xb5?\xc5\xf8\x85:r\x99\x03\xd9\xc9\xdb\xc2\xa0\xa01Js_of_ocaml__File\x900\x90\xf9I\xd23Q\xa6W+J\xb2\xd4\x9a\xeaM\xf6\xa0\xa05Js_of_ocaml__Dom_html\x900\xedMV\xa6za\xb0]\x8cy\xb5\x04xq\xb7W\xa0\xa00Js_of_ocaml__Dom\x900\xb7\x88ei\xb1Q\x0e\x9d\xe7\b[\x9by\xa4\xad\x8b\xa0\xa0-Js_of_ocaml__\x900\xcaj\xb7\x86\x16\t\xf3\xe0A\xc5\xee>Dn\x9f\x1f\xa0\xa0+Js_of_ocaml\x9006@}(\xe5\x12|@\x7f\xe4Gs\xe0\xd2\x1f\x07\xa0\xa0-Graphics_js__\x900\xab\x064\xce\x85\xe1\x81\xb8\xfd\x1ff\xa5\xd3G\x18\xf4\xa0\xa0+Graphics_js\x900\xa4\x99\xa9I\xb8\x94c<\x18V\xfc\x13\xa4K\xc0\x9a\xa0\xa0(Graphics\x9005\xa2\xa4\x85}\x8d\x124\xee^j\xae;^\x01\xa0\xa0\xa0)Dune__exe\x900\xf7\x89\x12\x11g'<\xecF\x04{8\x98\xa8\x06P\xa0\xa08CamlinternalFormatBasics\x900\xce\xcf\xaf\xd5\xc0!G?^5\x8c\x96\xacu\x02\xa0@\x84\x95\xa6\xbe\0\0\0\b\0\0\0\x04\0\0\0\x0b\0\0\0\x0b\xa0@\xa0A\xa0\x90@@");
   var
    global_data = runtime.caml_get_global_data(),
    Graphics_js = global_data.Graphics_js;
   function init(elt, cont){
    return caml_cps_call2(Graphics_js[40], elt, cont);
   }
   var Dune_exe_Graphics_support = [0, init];
   runtime.caml_register_global
    (1, Dune_exe_Graphics_support, "Dune__exe__Graphics_support");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIudG9wbGV2ZWwuZW9ianMvanNvby9kdW5lX19leGVfX0dyYXBoaWNzX3N1cHBvcnQuY21vLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbImluaXQiLCJlbHQiXSwic291cmNlcyI6WyIvd29ya3NwYWNlX3Jvb3QvZ3JhcGhpY3Nfc3VwcG9ydC5lbmFibGVkLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Rzs7Ozs7Ozs7Ozs7Ozs7Ozs7WUFBSUEsS0FBS0M7SUFBTSxPQUFBLGdDQUFOQTtHQUFpQzt1Q0FBdENEOzs7O0UiLCJzb3VyY2VzQ29udGVudCI6WyJsZXQgaW5pdCBlbHQgPSBHcmFwaGljc19qcy5vcGVuX2NhbnZhcyBlbHRcbiJdfQ==
