// Generated by js_of_ocaml
//# buildInfo:effects=true, kind=cmo, use-js-string=true, version=5.7.1+5.7.1

//# unitInfo: Provides: Dune__exe__Ocp_indent
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.jsoo_create_file
    ("/static/cmis/dune__exe__Ocp_indent.cmi",
     "Caml1999I032\x84\x95\xa6\xbe\0\0\0|\0\0\0\x13\0\0\0T\0\0\0N\xa05Dune__exe__Ocp_indent\xa0\xb0\xa0&indent\x01\x01\x17\xd0\xc0\xc1@\xc0\x90@\x02\x05\xf5\xe1\0@\0\xfc\xc0\xc1@\xc0\x04\x04\x02\x05\xf5\xe1\0@\0\xfb\x04\x05@\x02\x05\xf5\xe1\0@\0\xfd@\x02\x05\xf5\xe1\0@\0\xfe@\xb0\xc02ocp_indent.fake.mlAY]\xc0\x04\x02AYc@@\xa1\x04\x12@@@\x84\x95\xa6\xbe\0\0\0\x91\0\0\0\x14\0\0\0N\0\0\0>\xa0\xa05Dune__exe__Ocp_indent\x900\xbf\xf8\xe6$\xb5\xf8x\x17\x8a\xe5E\xa5\x02\xa6\x07\x8a\xa0\xa0&Stdlib\x900\x85\xf8]\xdbG\xed\xc0\xc7W\x96W\xee\xe7@0-\xa0\xa0)Dune__exe\x900\xf7\x89\x12\x11g'<\xecF\x04{8\x98\xa8\x06P\xa0\xa08CamlinternalFormatBasics\x900\xce\xcf\xaf\xd5\xc0!G?^5\x8c\x96\xacu\x02\xa0@\x84\x95\xa6\xbe\0\0\0\b\0\0\0\x04\0\0\0\x0b\0\0\0\x0b\xa0@\xa0A\xa0\x90@@");
   function indent(s, in_lines, cont){return cont(s);}
   var Dune_exe_Ocp_indent = [0, indent];
   runtime.caml_register_global
    (0, Dune_exe_Ocp_indent, "Dune__exe__Ocp_indent");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIudG9wbGV2ZWwuZW9ianMvanNvby9kdW5lX19leGVfX09jcF9pbmRlbnQuY21vLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbImluZGVudCIsInMiLCJpbl9saW5lcyJdLCJzb3VyY2VzIjpbIi93b3Jrc3BhY2Vfcm9vdC9vY3BfaW5kZW50LmZha2UubWwiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7O1lBQUlBLE9BQU9DLEdBQUVDLGdCQUFZLFlBQWRELEdBQWU7aUNBQXRCRDs7OztFIiwic291cmNlc0NvbnRlbnQiOlsibGV0IGluZGVudCBzIF9pbl9saW5lcyA9IHNcblxuKCogb2NwLWluZGVudCBub3QgYXZhaWxhYmxlICopXG4iXX0=
