// Generated by js_of_ocaml
//# buildInfo:effects=true, kind=cmo, use-js-string=true, version=5.7.1+5.7.1

//# unitInfo: Provides: Dune__exe
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   runtime.jsoo_create_file
    ("/static/cmis/dune__exe.cmi",
     "Caml1999I032\x84\x95\xa6\xbe\0\0\x02\x03\0\0\0^\0\0\x01q\0\0\x01T\xa0)Dune__exe\xa0\xd3\xa0#B64KA\xc0\x93\x90\x92.Dune__exe__B64@\xb0\xc0\t .toplevel.eobjs/dune__exe.ml-genDyy\xc0\x04\x02Dy\0T@\xa1\x04\x0f@@@\xa0\xd3\xa0(ColorizeLA\xc0\x93\x90\x923Dune__exe__Colorize@\xb0\xc0\x04\x0eG\0{\0{\xc0\x04\x0fG\0{\x01\0\xa0@\xa1\x04\x1cA@@\xa0\xd3\xa00Graphics_supportMA\xc0\x93\x90\x92;Dune__exe__Graphics_support@\xb0\xc0\x04\x1bJ\x01\0\xcf\x01\0\xcf\xc0\x04\x1cJ\x01\0\xcf\x01\x01\x04@\xa1\x04)B@@\xa0\xd3\xa0&IndentNA\xc0\x93\x90\x921Dune__exe__Indent@\xb0\xc0\x04(M\x01\x01)\x01\x01)\xc0\x04)M\x01\x01)\x01\x01J@\xa1\x046C@@\xa0\xd3\xa0*Ocp_indentOA\xc0\x93\x90\x925Dune__exe__Ocp_indent@\xb0\xc0\x045P\x01\x01s\x01\x01s\xc0\x046P\x01\x01s\x01\x01\x9c@\xa1\x04CD@@\xa0\xd3\xa0+Ppx_supportPA\xc0\x93\x90\x926Dune__exe__Ppx_support@\xb0\xc0\x04BS\x01\x01\xc6\x01\x01\xc6\xc0\x04CS\x01\x01\xc6\x01\x01\xf1@\xa1\x04PE@@\xa0\xd3\xa0(ToplevelQA\xc0\x93\x90\x923Dune__exe__Toplevel@\xb0\xc0\x04OV\x01\x02\x18\x01\x02\x18\xc0\x04PV\x01\x02\x18\x01\x02=@\xa1\x04]F@@@\x84\x95\xa6\xbe\0\0\0\xc6\0\0\0\x1a\0\0\0i\0\0\0U\xa0\xa0)Dune__exe\x900\xf7\x89\x12\x11g'<\xecF\x04{8\x98\xa8\x06P\xa0\xa03Dune__exe__Toplevel@\xa0\xa06Dune__exe__Ppx_support@\xa0\xa05Dune__exe__Ocp_indent@\xa0\xa01Dune__exe__Indent@\xa0\xa0;Dune__exe__Graphics_support@\xa0\xa03Dune__exe__Colorize@\xa0\xa0.Dune__exe__B64@@\x84\x95\xa6\xbe\0\0\0\x06\0\0\0\x03\0\0\0\b\0\0\0\b\xa0A\xa0\x90@@");
   var Dune_exe = [0];
   runtime.caml_register_global(0, Dune_exe, "Dune__exe");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIudG9wbGV2ZWwuZW9ianMvanNvby9kdW5lX19leGUuY21vLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbXSwic291cmNlcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7OztFIiwic291cmNlc0NvbnRlbnQiOltdfQ==
